export const INITIAL_DETAILS = 'INITIAL_DETAILS';
export const PROJECT_NAME = 'PROJECT_NAME';
export const USER_DETAILS = 'USER_DETAILS';
export const BREAKDOWN_DETAILS = 'BREAKDOWN_DETAILS';
export const ADD_BREAKDOWN_DETAILS = 'ADD_BREAKDOWN_DETAILS';